from typing import List, Optional, Dict
from sqlalchemy import select, func
from sqlalchemy.orm import Session
from sqlalchemy.exc import IntegrityError

from app.models.lead import Lead
from app.repositories.base import AbstractLeadRepository
from app.exceptions import DuplicateEmail

class SQLAlchemyLeadRepository(AbstractLeadRepository):
    """
    SQLAlchemy 2.0 implementation of the AbstractLeadRepository.
    """
    def __init__(self, db_session: Session):
        self.session = db_session

    def create(self, lead: Lead) -> Lead:
        try:
            self.session.add(lead)
            self.session.flush()  # Obtain autogenerated PK
            return lead
        except IntegrityError as e:
            # Detect unique email constraint violation and raise domain error
            if "uq_lead_email" in str(e) or "email" in str(e).lower():
                raise DuplicateEmail(f"A lead with email '{lead.email}' is already registered.")
            raise e

    def get_by_id(self, lead_id: int) -> Optional[Lead]:
        return self.session.get(Lead, lead_id)

    def get_by_email(self, email: str) -> Optional[Lead]:
        stmt = select(Lead).filter(Lead.email == email)
        return self.session.execute(stmt).scalars().first()

    def list(
        self,
        status: Optional[str] = None,
        query: Optional[str] = None,
        skip: int = 0,
        limit: int = 100
    ) -> List[Lead]:
        stmt = select(Lead)
        
        if status is not None:
            stmt = stmt.filter(Lead.status == status)
            
        if query is not None and query.strip() != "":
            # ILIKE partial match on name, email, or company
            search_pattern = f"%{query}%"
            stmt = stmt.filter(
                (Lead.name.ilike(search_pattern)) |
                (Lead.email.ilike(search_pattern)) |
                (Lead.company.ilike(search_pattern))
            )
            
        # Order by created_at DESC and apply pagination
        stmt = stmt.order_by(Lead.created_at.desc(), Lead.id.desc()).offset(skip).limit(limit)
        return list(self.session.execute(stmt).scalars().all())

    def update(self, lead: Lead) -> Lead:
        try:
            # Flush pending modifications to the DB
            self.session.flush()
            # Refresh the ORM instance to reload server-generated values (e.g. updated_at)
            # from the database, preventing stale data in the API response (B-03).
            self.session.refresh(lead)
            return lead
        except IntegrityError as e:
            if "uq_lead_email" in str(e) or "email" in str(e).lower():
                raise DuplicateEmail(f"A lead with email '{lead.email}' is already registered.")
            raise e

    def delete(self, lead_id: int) -> None:
        lead = self.get_by_id(lead_id)
        if lead:
            self.session.delete(lead)
            self.session.flush()

    def get_metrics(self) -> Dict[str, int]:
        stmt = select(Lead.status, func.count(Lead.id)).group_by(Lead.status)
        results = self.session.execute(stmt).all()
        return {status: count for status, count in results}
