from typing import List
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models.lead_activity import LeadActivity
from app.repositories.base import AbstractLeadActivityRepository

class SQLAlchemyLeadActivityRepository(AbstractLeadActivityRepository):
    """
    SQLAlchemy 2.0 implementation of the AbstractLeadActivityRepository.
    """
    def __init__(self, db_session: Session):
        self.session = db_session

    def create(self, activity: LeadActivity) -> LeadActivity:
        self.session.add(activity)
        self.session.flush()  # Obtain autogenerated PK
        return activity

    def list_by_lead_id(self, lead_id: int) -> List[LeadActivity]:
        stmt = select(LeadActivity).filter(
            LeadActivity.lead_id == lead_id
        ).order_by(LeadActivity.created_at.desc(), LeadActivity.id.desc())
        return list(self.session.execute(stmt).scalars().all())
