"""0001_initial_migration

Revision ID: 7d4ba69b71aa
Revises: 
Create Date: 2026-06-19 08:06:42.101093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d4ba69b71aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('NEW', 'CONTACTED', 'QUALIFIED', 'LOST')", name='chk_lead_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_lead_email')
    )
    op.create_index('idx_leads_status_created_at', 'leads', ['status', 'created_at'], unique=False)
    op.create_table('lead_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("type IN ('CALL', 'EMAIL', 'NOTE')", name='chk_lead_activity_type'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_activities')
    op.drop_index('idx_leads_status_created_at', table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
